application: date-map
version: hello
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /jqry
  static_dir: jqry
- url: /intro
  static_dir: intro
- url: /(.*)\.ico
  static_files: /\1.ico
  upload: (.*)\.ico
- url: /admin/.*
  script: admin.py
  login: admin
- url: /task/.*
  script: task.py
  login: admin
- url: /.*
  script: main.py
