application: date-map
version: alpaca
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /example.html
  static_files: example.html
  upload: example.html
- url: /.*
  script: main.py
